# -*- coding: utf-8 -*-
"""pca_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X1CXG9eg3C7wgQm14UinGjwp8rdljce3
"""

import numpy as np
from sklearn.decomposition import PCA
from PIL import Image

faces = Image.open('/Users/ronnitburman/Downloads/CroppedYale/yaleB02/yaleB02_P00A-010E+00.pgm') #face from yale dataset 

h, w = faces.shape
X = np.reshape(faces.images, (1240, 1034))
pca = PCA(n_components=5)
pca.fit(X)

X_firstReshape = np.reshape(pca.components_[0], (h,w))
plt.imshow(X_firstReshape , cmap='bone')

fig, ax = plt.subplots(5, 10, figsize=(9, 5),
                       subplot_kw={'xticks':[], 'yticks':[]},
                       gridspec_kw=dict(hspace=0.1, wspace=0.1))
list_eigenfaces = []
k = 0 
for i in range(50):
   eigenface = np.reshape(pca.components_[i], (h,w))
   list_eigenfaces.append(eigenface)

for i in range(5):
    for j in range(10):
      ax[i][j].imshow(list_eigenfaces[k], cmap='binary_r')
      k+=1